### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/project-reporting#18]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] project_billing_utils - By @Chandresh-SerpentCS - #27
- [ ] project_indicators - By @Chandresh-SerpentCS - #26 
- [x] project_task_report - By @Chandresh-SerpentCS - #25

**Comment by emagdalenaC2i** [comment]
There is a PR for the migration of project_billing_utils - By @Chandresh-SerpentCS - #27 
There is a PR for the migration of project_indicators - By @Chandresh-SerpentCS - #26
